services:
  gateway:
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_started
      fraud-service:
        condition: service_started
      wallet-service:
        condition: service_started
      transaction-service:
        condition: service_started
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      gateway:
        condition: service_started
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:12.4.2
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      # --- Seguridad ---
      GF_USERS_ALLOW_SIGN_UP: "false" # nadie se puede registrar solo
      GF_AUTH_DISABLE_LOGIN_FORM: "false" # dejamos login normal activo
      GF_SECURITY_DISABLE_GRAVATAR: "true" # no hace requests externos
      GF_ANALYTICS_REPORTING_ENABLED: "false" # no envía telemetría a Grafana Labs
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false" # no hace requests externos
      GF_SNAPSHOTS_EXTERNAL_ENABLED: "false" # deshabilita snapshots públicos
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped

  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  fraud-service:
    build:
      context: ..
      dockerfile: services/fraud-service/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped

  wallet-service:
    build:
      context: ..
      dockerfile: services/wallet-service/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  transaction-service:
    build:
      context: ..
      dockerfile: services/transaction-service/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: peer-ledger-postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ../db/migrations/01_users.sql:/docker-entrypoint-initdb.d/01_users.sql:ro
      - ../db/migrations/02_wallets.sql:/docker-entrypoint-initdb.d/02_wallets.sql:ro
      - ../db/migrations/03_transactions.sql:/docker-entrypoint-initdb.d/03_transactions.sql:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
